# Generated by Django 6.0 on 2025-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inacook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta_ingrediente',
            name='peso',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='receta_ingrediente',
            name='peso_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
